# Generated by Django 3.1.7 on 2021-02-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210228_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'Распродажа'), (2, 'Популярный'), (3, 'Новинка'), (4, 'Заканчивается'), (5, '')], default=5, verbose_name='Статус'),
        ),
    ]
